theme: jekyll-theme-slate
title: Twitterwall2
description:  Twitterwall with spring:boot for heroku using spring-integration for MQ and spring-data-jpa for PostgreSQL
google_analytics: UA-17174370-7

