package org.woehlke.twitterwall.oodm.model.tasks;

/**
 * Created by tw on 09.07.17.
 */
public enum TaskType {

    NULL,
    FETCH_TWEETS_FROM_SEARCH,
    FETCH_HOME_TIMELINE,
    FETCH_USER_TIMELINE,
    FETCH_MENTIONS,
    FETCH_FAVORITES,
    FETCH_RETWEETS_OF_ME,
    FETCH_LISTS,
    FETCH_USERS_FROM_LIST,
    FETCH_LISTS_FOR_USERS,
    FETCH_USERLIST_OWNERS,
    FETCH_FOLLOWER,
    FETCH_FRIENDS,
    UPDATE_TWEETS,
    UPDATE_USERS,
    UPDATE_MENTIONS_FOR_USERS,
    UPDATE_URLS,
    CREATE_IMPRINT_USER,
    CREATE_TESTDATA_TWEETS,
    CREATE_TESTDATA_USERS,
    REMOVE_OLD_DATA_FROM_STORAGE,
    GARBAGE_COLLECTION
}
